# Generated by Django 4.2.3 on 2023-07-15 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_stock_date_alter_stock_inferior_limit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='date',
            new_name='updated_at',
        ),
    ]
