# Generated by Django 4.2.3 on 2023-07-19 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_asset_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='asset',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
