# Generated by Django 4.2.3 on 2023-07-20 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_delete_user_asset_email_sent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='email_sent',
            new_name='email_sent_status',
        ),
    ]
